Add support for repeated fields
metaverse/truss pull request #62
Opened 2016-09-28 23:20 UTC by hasLeland

Adds support for repeated fields in http transport generation and within client argument handling.

## Client and Server Repeated Fields

Let's say you where to use our `addsvc` proto file, but set the `A` field of SumRequest to be `repeated`. This implies a slice of int64 instead of a single int64. So, on the command line, you'd type:

    $ addsvc-client -http.addr=:8081 -sum.a "[1,3]" -sum.b 2

And the server would respond like so:

    Encoding request a:1 a:3 b:2 
    URL: http://:8081/sum?a=1&a=3&b=2
    Client Requested with:
    [1 3] 2
    Server Responded with:
    v:6 

## What is NOT added

### Repeated fields in the Path are forbidden

This does NOT add support for repeated fields within the path of an HTTP request, because:

1. There was no reliable way to do this
2. It is something that is totally unsupported by other HTTP frameworks/libraries because of reason 1

However, if you try to put a repeated field into the path, Truss will now provide a nice warning telling you not to put a repeated field into the path.

### This does NOT add support for nested messages

Additionally, this does NOT add support for arbitrarily nested messages. If you try to nest a message or use a map, Truss will now warn you about how those things are not supported.

2016-09-29 03:08 UTC, hasIan requested changes
Overall, looks very well thought out. Because I am not in your head and haven't thought about the conceptual problem you're addressing with these changes, and also because this is a large PR, this review was mainly cursory, as you can tell from the largely style-centric nature of the comments.

2016-09-29 03:08 UTC, hasIan commented on gengokit/clientarggen/client_argument_generator.go
> +	// FlagArg is the name of the Go variable that will hold the result of
Use consistent vertical spacing inside a struct definition. Suggest leaving a blank line before the documentation comments, as you have after `Name`.

2016-09-29 03:08 UTC, hasIan commented on gengokit/clientarggen/client_argument_generator.go
>  	fType := ""
When you don't need to set an initial value, prefer the `var fType string` form.

2016-09-29 03:08 UTC, hasIan commented on gengokit/clientarggen/client_argument_generator_test.go
> +		Indent: "   ",
THREE spaces!? You savage!

2016-09-29 03:08 UTC, hasIan commented on gengokit/clientarggen/client_argument_generator_test.go
> +						GoConvertFunc:   "\nfunc CarveASum(inpt string) []int64 {\n\tinpt = strings.Trim(inpt, \"[] \")\n\tslc := strings.Split(inpt, \",\")\n\tvar rv []int64\n\n\tfor _, item := range slc {\n\t\titem
This is pretty gnarly. Generally, I try to keep lines no more than 100 characters long for readability's sake, but even neglecting this, the escape sequences impair readability. Define this as a raw string variable somewhere else and reference it in the assignment.

E.g.,

``` go
testGoConvertFunc := `
func CarveASum(input string) []int64 {
    input = strings.Trim(input, "[] ")
    slice := strings.Split(input, ",")
    var rv []int64

    for _, item := range slice {
        item = strings.Replace(item, "'", "\\", -1)
        if len(item) == 0 {
            continue
        }
        tmp, err := strconv.ParseInt(item, 10, 64)
        if err != nil {
            panic(fmt.Sprintf("couldn't parse %q of %q", item, input))
        }
        rv = append(rv, tmp)
    }
    return rv
}`

// ...
GoConvertFunc: testGoConvertFunc
```

2016-09-29 03:08 UTC, hasIan commented on gengokit/clientarggen/client_argument_generator_test.go
> +						FlagConvertFunc: "flagBSum = flag.Int64(\"sum.b\", 0, \"\")",
Again, use a raw string here (inline is fine) to eliminate the need to use all those backslashes.

2016-09-29 03:08 UTC, hasIan commented on gengokit/clientarggen/client_argument_generator_test.go
> +	if got, want := csa, expected; !reflect.DeepEqual(got, want) {
I saw this pattern in one of Adam's pull request and wondered where it came from, but it's even more bizarre here. You have a variable called `expected`, but instead of using it, you're assigning it to another variable called `want`. Further, the actual result is already in a variable called `csa`. Why not

```
if !reflect.DeepEqual(expected, csa) {
// ...
```

2016-09-29 03:08 UTC, hasIan commented on gengokit/clientarggen/strcarver.go
> +	code, err := ApplyTemplate("CarveInvocationTempl", invocTemplate, m, nil)
This is an odd abbreviation. "Tmpl" or "template" seem fine, but "Templ" is like you changed your mind about abbreviating halfway through typing "template."

I realize this is pretty nitpicky.

2016-09-29 03:08 UTC, hasIan commented on gengokit/clientarggen/strcarver.go
> +	invoc := ""
Use `var invoc string` to declare variable and assign implicit zero value.

2016-09-29 03:08 UTC, hasIan commented on gengokit/clientarggen/strcarver.go
> +
Generally speaking, aggressively expunge unnecessary vertical whitespace.

2016-09-29 03:08 UTC, hasIan commented on gengokit/clientarggen/templated.go
> +//
Blank comment and extra blank line.

2016-09-29 03:08 UTC, hasIan commented on gengokit/clientarggen/templated.go
> +			panic(fmt.Sprintf("couldn't parse '%v' of '%v'", item, inpt))
These are both strings; why not `"%q of %q"`?

2016-09-29 03:08 UTC, hasIan commented on gengokit/clientarggen/templated.go
> +func CarveUintthirtytwo(inpt string) []uint32 {
What's with the numbers written out in these function names? `sixtyfour`, `thirtytwo`. What am I missing?

2016-09-29 03:08 UTC, hasIan commented on gengokit/clientarggen/templated.go
> +func CarveBool(inpt string) []bool {
These `Carve` functions really make we want a generic of some sort. If it were not for the return values of each function. I wanted to otherwise suggest passing a parsing function to each. You could still do it like so, but it's probably not worth the additional complexity.

```
func Carve(input string, parser func(string) (interface{}, error)) []interface{} {
    input = strings.Trim(input, "[]")
    slice := strings.Split(input, ",")
    var rv []interface{}
    for _, item := range slice {
        item = strings.Trim(item, " ")
        item = strings.Replace(item, "'", `\`, -1)
        if len(item) == 0 {
            continue
        }
        tmp, err := parser(item)
        if err != nil {
            panic(fmt.Sprintf("could not parse %q of %q", item, input))
        }
        rv = append(rv, tmp)
    }
    return rv
}

func CarveFloat64(input string) []float64 {
    parser := func(input string) (interface{}, error) {
        return strconv.ParseFloat(input, 64)
    }
    intf := Carve(input, parser)
    floats := make([]float64, len(intf))
    for i, item := range intf {
        floats[i] = item.(float64)
    }
    return floats
}

```

[Carving in Action](https://play.golang.org/p/eTFNLfgxSi)

It reduces lines of code, and eliminates some repeated logic, but it has to unmarshal the return value from `Carve` into the desired type, so, not as elegant as it'd otherwise be.

2016-09-29 03:08 UTC, hasIan commented on gengokit/gentesthelper/helper.go
> +	text, _ := difflib.GetUnifiedDiffString(t)
Don't ignore errors.

2016-09-29 03:08 UTC, hasIan commented on gengokit/httptransport/httptransport.go
> +		if nField.IsBaseType == false {
This could be expressed as `!nField.IsBaseType`.

2016-09-29 03:08 UTC, hasIan commented on gengokit/httptransport/httptransport.go
> +			wrn := []string{
Just use string concatenation instead of this slice of strings thing.

```
wrn := "%s.%s is a repeated field specified to be in the path. " +
    "Currently, repeated fields are not supported in the path " +
    "and may result in generated code which fails to compile."
```

Also, I would drop the word "currently" from that message. It sort of implies that we will support repeated fields as path variables. I don't think that will ever happen. If it does, the place to communicate it is in a roadmap or a tagged Github issue, not an error message in the executable.

2016-09-29 03:08 UTC, hasIan commented on gengokit/clientarggen/templated.go
> +func CarveIntegerthirtytwo(inpt string) []int32 {
I don't know about the "carve" metaphor; it's creative, but in software, that's a synonym for "clever," and cleverness is bad in software. Better would be a name makes plain what's going on just by reading it, like `ExtractInt32Slice` or `ConvertToInt32Slice`.

2016-09-29 03:08 UTC, hasIan commented on gengokit/clientarggen/client_argument_generator.go
>  	tmp := []string{}
If you know how big your end slice is going to be, declare it as such.

```
args := make([]string, 0, len(ma))
```

2016-09-29 03:08 UTC, hasIan commented on gengokit/clientarggen/client_argument_generator.go
>  type MethodArgs struct {
There seems to be no reason to make this a struct. Why not just

```
type MethodArgs []*ClientArg

func (ma *MethodArgs) FunctionArgs() string {
    args := make([]string, 0, len(ma))
    for _, a :=  range ma {
        append(args, fmt.Sprintf("%s %s", a.GoArg, a.GoType))
    }
    return args
}
```

2016-09-29 03:08 UTC, hasIan commented on gengokit/clientarggen/client_argument_generator.go
> +// MarshalFlags returns the code for intantiating the GoArgs for this method
"intantiating"

2016-09-29 03:08 UTC, hasIan commented on gengokit/clientarggen/strcarver.go
> +func GenerateCarveFunc(m *ClientArg) string {
You have "carve" functions for the primitive types actually implemented in this PR. Why do you need to generate a string form of a function? The contents of the template are near identical to the functions that are already implemented. Am I missing something, or is there redundancy here?

2016-09-29 05:41 UTC, hasAdamr commented
Could we use `json.Unmarshal` for the "Carving" functionally? It takes json arrays as strings and unmashals them into whatever slice type you give it. i.e.

```
		a := []int32{1, 2, 3, 4}
		s := `[1,2,3 ,4 ]`
		var b []int32
		err := json.Unmarshal([]byte(s), &b)
```

I did a few here: https://play.golang.org/p/xAO6luCtWI

2016-09-29 06:25 UTC, hasAdamr commented on gengokit/httptransport/httptransport.go
> +				"Currently, repeated fields are not supported in the path ",
Wait, won't maps and nested messages work if they are json in the body of a http request? It will just be unmarshaled.

2016-09-29 06:26 UTC, hasAdamr commented on gengokit/httptransport/httptransport.go
> +				"types are supported. As a result, the generated HTTP ",
Wait won't maps and nested types work if there is json in the body of an http request? It will just be marshaled to the type.

2016-09-29 18:36 UTC, hasAdamr commented on gengokit/clientarggen/strcarver.go
> +		FlagType  string
Would this ever be something other than string.

2016-09-29 18:50 UTC, hasIan commented
I like Adam's comment about simply using the JSON parser to interpret the repeated arguments instead of implementing our own special-purpose subset-of-JSON parser. This will allow support for repeated arguments with much less code. Less code is better.

2016-10-06 01:00 UTC, hasAdamr commented
I'm closing this now. No reason to leave it open, features are being worked on in other pull requests and this is diverging.

2016-10-06 01:00 UTC, closed without merging